name: Code Check
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [21, 24]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Build
      run: |
        mvn \
          -Dmaven.compiler.release=${{ matrix.java-version }} \
          -Dmaven.compiler.source=${{ matrix.java-version }} \
          -Dmaven.compiler.target=${{ matrix.java-version }} \
          clean compile assembly:single
      working-directory: ./core
    
    - name: Run tests
      run: |
        mvn \
          -Dmaven.compiler.release=${{ matrix.java-version }} \
          -Dmaven.compiler.source=${{ matrix.java-version }} \
          -Dmaven.compiler.target=${{ matrix.java-version }} \
          test
      working-directory: ./core
      
    - name: Check code format
      run: |
        mvn \
          -Dmaven.compiler.release=${{ matrix.java-version }} \
          -Dmaven.compiler.source=${{ matrix.java-version }} \
          -Dmaven.compiler.target=${{ matrix.java-version }} \
          spotless:check
      continue-on-error: true
      working-directory: ./core
    
    - name: Run SpotBugs
      run: |
        mvn \
          -Dmaven.compiler.release=${{ matrix.java-version }} \
          -Dmaven.compiler.source=${{ matrix.java-version }} \
          -Dmaven.compiler.target=${{ matrix.java-version }} \
          spotbugs:check
      continue-on-error: true
      working-directory: ./core
    
    - name: Upload SpotBugs report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: spotbugs-report-java${{ matrix.java-version }}
        path: core/target/spotbugs*
        if-no-files-found: ignore
    - name: Run Checkstyle
      run: |
        mvn \
          -Dmaven.compiler.release=${{ matrix.java-version }} \
          -Dmaven.compiler.source=${{ matrix.java-version }} \
          -Dmaven.compiler.target=${{ matrix.java-version }} \
          checkstyle:check
      continue-on-error: true
      working-directory: ./core
      
    - name: Upload Checkstyle report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: checkstyle-report-java${{ matrix.java-version }}
        path: core/target/checkstyle-result.xml
        if-no-files-found: ignore
        
    - name: Run PMD
      run: |
        mvn \
          -Dmaven.compiler.release=${{ matrix.java-version }} \
          -Dmaven.compiler.source=${{ matrix.java-version }} \
          -Dmaven.compiler.target=${{ matrix.java-version }} \
          pmd:check
      continue-on-error: true
      working-directory: ./core
      
    - name: Upload PMD report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: pmd-report-java${{ matrix.java-version }}
        path: core/target/pmd.xml
        if-no-files-found: ignore