name: Code Quality

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('core/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run Code Quality Checks
      run: mvn clean verify -q
      working-directory: ./core
      continue-on-error: true

    - name: Archive analysis results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: code-quality-reports
        path: |
          core/target/checkstyle-result.xml
          core/target/spotbugsXml.xml
          core/target/pmd.xml
          core/target/dependency-check-report.html