name: Code Check

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build
      run: mvn clean compile assembly:single
      working-directory: ./core
    
    - name: Check formatting
      run: mvn formatter:validate
      working-directory: ./core
    
    - name: Run SpotBugs
      run: mvn spotbugs:check
      continue-on-error: false
      working-directory: ./core
    
    - name: Check dependencies
      run: mvn dependency-check:check
      continue-on-error: false
      working-directory: ./core
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: target/surefire-reports/
    
    - name: Upload SpotBugs report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: spotbugs-report
        path: target/spotbugs*
    
    - name: Upload dependency check report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dependency-report
        path: target/dependency-check-report.*