name: Core Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11, 17, 21, 24]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run tests
      run: mvn clean test
      working-directory: ./core

    - name: Combine test summaries
      if: success() || failure()
      run: |
        mkdir -p core/target/surefire-reports
        COMBINED=core/target/surefire-reports/test-summary-${{ matrix.java-version }}.txt
        > "$COMBINED"
        for f in core/target/surefire-reports/*.txt; do
          echo "\n---- $f ----\n" >> "$COMBINED"
          cat "$f" >> "$COMBINED"
        done
      shell: bash

    - name: Upload combined test summary
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-summary
        path: core/target/surefire-reports/test-summary-${{ matrix.java-version }}.txt